name: Linux 64
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          version: 110.0.5481.30
          arch: linux64
          download-path: temp
