name: Mac 64
on: [push]
jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        run: sh ./download
        with:
          download-path: temp
          version: 110.0.5481.30
          arch: mac64
