name: Windows 32
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./action
        with:
          download-path: temp
          version: 110.0.5481.30
          arch: wind32
